### ISSUE TITLE
Please consider adding to homebrew / brew.sh

### ISSUE THREAD

**Issue by jasonm23** [smokris/GetWindowID#3]
Very handy little utility.

**Comment by smokris** [comment]
Thanks, @jasonm23!

However, this utility doesn't meet [Homebrew's requirements](https://docs.brew.sh/Acceptable-Formulae.html#niche-or-self-submitted-stuff) ("GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)"), and as the author I'm not permitted to submit it ("We frown on authors submitting their own work").

I'll leave this issue open, in case more people eventually follow it on GitHub (in which case somebody who isn't the author could submit it).

**Comment by jasonm23** [comment]
This is true, however, it's simple and to setup a brew tap.

If you like I can do it for you over the weekend.

**Comment by smokris** [comment]
OK, I created a tap.  You can now install GetWindowID by running:

    brew install smokris/getwindowid/getwindowid

**Comment by jasonm23** [comment]
:+1: great stuff
