### ISSUE TITLE
Catalina adaption

### ISSUE THREAD

**Issue by ingski** [smokris/GetWindowID#6]
Using the latest macOS 10.15 (Catalina) unfortunately GetWindowID is broken.
For example 

GetWindowID Safari --list

produces a list of windows where instead of the names "(null)" is listed.
Also

GetWindowID "${appname}" "${windowname}"`

with correct values for both returns no id any more :-(

**Comment by smokris** [comment]
Yeah, unfortunately in macOS 10.15 the `CGWindowListCopyWindowInfo()` API no longer provides access to titles of other processes' windows.  I also tried, unsuccessfully, to get that info using the old Carbon `CopyWindowTitleAsCFString` API and the private `CGSCopyWindowProperty` API.  I eventually got it to work using the Accessibility API.

**Comment by smokris** [comment]
I tagged version 1.1 which includes this fix.

**Comment by ingski** [comment]
Great. Thanks a lot for this update 👍😃
